branch-defaults:
  master:
    environment: node-express-env
    group_suffix: null
global:
  application_name: .StreetDirectory
  branch: null
  default_ec2_keyname: null
  default_platform: node.js
  default_region: ap-southeast-2
  profile: eb-cli
  repository: null
  sc: git
